import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { recordId, drug, sku, qty, loss, status, processedBy } = body;

    const isApproved = status === 'APPROVED';
    const statusColor = isApproved ? '#10b981' : '#f43f5e'; // Emerald or Rose

    const formattedLoss = typeof loss === 'number' 
      ? loss.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
      : loss || '0.00';

    // Professional Audit HTML Email Template
    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 24px; text-align: center;">
          <h2 style="color: #ffffff; margin: 0; font-style: italic; font-weight: 900; letter-spacing: -0.5px;">
            GAM Med <span style="color: #f43f5e;">Pharmacy & Supply Chain</span>
          </h2>
          <p style="color: #94a3b8; margin: 4px 0 0 0; font-size: 12px; font-weight: 500;">Clinical Disposal Audit Notification</p>
        </div>
        <div style="padding: 30px;">
          <h3 style="color: #334155; margin-top: 0; font-size: 18px;">Disposal Audit Log #${recordId}</h3>
          <p style="color: #64748b; font-size: 14px; line-height: 1.5;">
            A pharmaceutical stock disposal request has been marked as 
            <strong style="color: ${statusColor}; text-transform: uppercase;">${status}</strong>.
          </p>
          
          <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px;">
            <tr style="border-bottom: 1px solid #e2e8f0;">
              <td style="padding: 12px 0; color: #64748b;">Record ID:</td>
              <td style="padding: 12px 0; color: #0f172a; font-weight: bold; text-align: right; font-family: monospace;">#${recordId}</td>
            </tr>
            <tr style="border-bottom: 1px solid #e2e8f0;">
              <td style="padding: 12px 0; color: #64748b;">Product Name:</td>
              <td style="padding: 12px 0; color: #0f172a; font-weight: bold; text-align: right;">${drug} <span style="color: #6366f1; font-family: monospace; font-size: 12px;">(${sku})</span></td>
            </tr>
            <tr style="border-bottom: 1px solid #e2e8f0;">
              <td style="padding: 12px 0; color: #64748b;">Decommissioned Quantity:</td>
              <td style="padding: 12px 0; color: #0f172a; font-weight: bold; text-align: right;">${qty} Units</td>
            </tr>
            <tr style="border-bottom: 1px solid #e2e8f0;">
              <td style="padding: 12px 0; color: #64748b;">Financial Impact:</td>
              <td style="padding: 12px 0; color: ${isApproved ? '#f43f5e' : '#94a3b8'}; font-weight: bold; text-align: right; ${!isApproved ? 'text-decoration: line-through;' : ''}">
                ₵ ${formattedLoss}
              </td>
            </tr>
          </table>

          <div style="margin-top: 30px; padding: 16px; background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; font-size: 12px; color: #64748b;">
            <div style="margin-bottom: 4px;">Auditor / Supervisor: <strong>${processedBy || 'Pharmacy Director'}</strong></div>
            <div>Timestamp: <strong>${new Date().toLocaleString()}</strong></div>
          </div>

          <div style="margin-top: 20px; text-align: center; font-size: 11px; color: #94a3b8;">
            This is an automated audit receipt generated by GAM Med Health Enterprise Systems.
          </div>
        </div>
      </div>
    `;

    console.log(`[DISPOSAL NOTIFICATION EMAIL DISPATCHED] Record #${recordId} - Status: ${status} - Processed By: ${processedBy}`);

    return NextResponse.json({ 
      success: true, 
      message: 'Audit notification receipt dispatched.',
      recordId,
      status,
      timestamp: new Date().toISOString(),
      emailPreviewHtml: emailHtml
    });

  } catch (error: any) {
    console.error('Email Dispatch Error:', error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
