
'use client';

import * as React from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { toast } from '@/hooks/use-toast';
import { User } from '@/lib/types';
import Image from 'next/image';

interface EnableMfaDialogProps {
  user: User;
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  onMfaEnabled: () => void;
}

export function EnableMfaDialog({ user, isOpen, onOpenChange, onMfaEnabled }: EnableMfaDialogProps) {
  const [step, setStep] = React.useState<'scan' | 'verify'>('scan');
  const [verificationCode, setVerificationCode] = React.useState('');
  const [isVerifying, setIsVerifying] = React.useState(false);

  // In a real app, this would be a unique secret generated by the server.
  const qrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=otpauth://totp/GamMed:${user.email}?secret=JBSWY3DPEHPK3PXP&issuer=GamMed`;

  const handleVerify = async () => {
    setIsVerifying(true);
    // In a real app, this would call a server action `verifyMfaCode(verificationCode)`
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    if (verificationCode === '123456') { // Simulate successful verification
      onMfaEnabled();
      toast.success('MFA Enabled Successfully', {
        description: 'Multi-factor authentication has been enabled for your account.',
      });
      onOpenChange(false);
    } else {
      toast.error('Invalid Verification Code', {
        description: 'The code you entered is incorrect. Please try again.',
      });
    }
    setIsVerifying(false);
  };
  
  React.useEffect(() => {
    if(!isOpen) {
        setStep('scan');
        setVerificationCode('');
    }
  }, [isOpen])

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Enable Multi-Factor Authentication</DialogTitle>
          <DialogDescription>
            {step === 'scan'
              ? 'Scan the QR code below with your authenticator app (e.g., Google Authenticator).'
              : 'Enter the 6-digit code from your authenticator app to complete the setup.'}
          </DialogDescription>
        </DialogHeader>
        <div className="py-4 flex items-center justify-center">
            {step === 'scan' ? (
                <Image src={qrCodeUrl} alt="MFA QR Code" width={200} height={200} />
            ) : (
                <div className="w-full max-w-xs">
                     <Input 
                        placeholder="123 456" 
                        value={verificationCode}
                        onChange={(e) => setVerificationCode(e.target.value)}
                     />
                </div>
            )}
        </div>
        <DialogFooter>
          <Button variant="ghost" onClick={() => onOpenChange(false)}>Cancel</Button>
          {step === 'scan' ? (
            <Button onClick={() => setStep('verify')}>Next</Button>
          ) : (
             <Button onClick={handleVerify} disabled={isVerifying || verificationCode.length < 6}>
                {isVerifying ? 'Verifying...' : 'Verify & Enable'}
             </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
