import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const {
      hospitalId,
      pvNumber,
      disbursementMode,
      grossAmount,
      netAmount,
      payeeCount,
      narration,
      makerName,
      checkerEmail,
      checkerPhone
    } = body;

    const formattedNet = (netAmount || 0).toLocaleString("en-US", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    });

    const isBatch = disbursementMode === "BATCH";
    const title = isBatch
      ? `Batch PV #${pvNumber} (${payeeCount || 1} Payees) Awaiting Checker Approval`
      : `Payment Voucher #${pvNumber} Awaiting Checker Approval`;

    const deepLink = `https://gam-med.vercel.app/accountant/payments/archive`;

    // 1. Prepare Email Payload (Resend / SendGrid Standard)
    const emailPayload = {
      to: checkerEmail || "chief_accountant@gam-med.com",
      subject: `🚨 [GAM MED ACTION REQUIRED] ${title}`,
      html: `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; background: #090d16; color: #ffffff; padding: 32px; border-radius: 16px; border: 1px solid #1e293b;">
          <div style="display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #1e293b; padding-bottom: 16px; margin-bottom: 24px;">
            <h2 style="margin: 0; color: #10b981; font-size: 20px; text-transform: uppercase; letter-spacing: 1px;">GAM Med Treasury Alert</h2>
            <span style="background: rgba(16, 185, 129, 0.15); color: #10b981; padding: 4px 10px; border-radius: 6px; font-size: 11px; font-weight: bold; border: 1px solid rgba(16, 185, 129, 0.3);">MAKER-CHECKER QUEUE</span>
          </div>

          <p style="color: #94a3b8; font-size: 14px; margin-bottom: 20px;">
            <strong>${makerName || "Preparer (Maker)"}</strong> has submitted a new ${isBatch ? "multi-payee batch disbursement" : "commercial payment voucher"} for your review and authorization.
          </p>

          <div style="background: #0f172a; border: 1px solid #334155; border-radius: 12px; padding: 20px; margin-bottom: 24px;">
            <table style="width: 100%; font-size: 13px; color: #cbd5e1; border-collapse: collapse;">
              <tr>
                <td style="padding: 6px 0; color: #64748b;">Voucher Number:</td>
                <td style="padding: 6px 0; font-family: monospace; font-weight: bold; text-align: right; color: #ffffff;">${pvNumber}</td>
              </tr>
              <tr>
                <td style="padding: 6px 0; color: #64748b;">Batch Type:</td>
                <td style="padding: 6px 0; font-weight: bold; text-align: right; color: #a5b4fc;">${isBatch ? `Batch (${payeeCount} Payees)` : "Single Commercial Vendor"}</td>
              </tr>
              <tr>
                <td style="padding: 6px 0; color: #64748b;">Disbursement Purpose:</td>
                <td style="padding: 6px 0; text-align: right; color: #cbd5e1;">${narration || "Clinical Staff Allowances"}</td>
              </tr>
              <tr style="border-top: 1px solid #1e293b;">
                <td style="padding: 12px 0 6px 0; font-size: 14px; font-weight: bold; color: #10b981;">Net Outflow:</td>
                <td style="padding: 12px 0 6px 0; font-family: monospace; font-size: 18px; font-weight: 900; text-align: right; color: #10b981;">GHS ${formattedNet}</td>
              </tr>
            </table>
          </div>

          <div style="text-align: center; margin: 32px 0;">
            <a href="${deepLink}" style="background: #10b981; color: #ffffff; text-decoration: none; padding: 14px 28px; border-radius: 10px; font-weight: bold; font-size: 14px; display: inline-block; box-shadow: 0 4px 14px rgba(16, 185, 129, 0.4);">
              Authorize Voucher in Checker Queue →
            </a>
          </div>

          <p style="color: #64748b; font-size: 11px; text-align: center; margin-top: 24px; border-top: 1px solid #1e293b; padding-top: 16px;">
            Confidential financial notification generated by GAM Med IPSAS-Compliant General Ledger System.
          </p>
        </div>
      `,
    };

    // 2. Prepare SMS Message (Africa's Talking / Arkesel / Twilio)
    const smsMessage = `GAM MED ALERT: Maker (${makerName || "Finance"}) submitted PV #${pvNumber} (${isBatch ? `${payeeCount} Payees, ` : ""}GHS ${formattedNet} Net) for Checker sign-off. Approve: ${deepLink}`;

    // 3. Dispatch to SMS Gateway if configured
    let smsStatus = "SIMULATED";
    const arkeselApiKey = process.env.ARKESEL_SMS_API_KEY || process.env.SMS_API_KEY;
    if (arkeselApiKey && checkerPhone) {
      try {
        const smsRes = await fetch("https://api.arkesel.com/sms/v2/sms/send", {
          method: "POST",
          headers: {
            "api-key": arkeselApiKey,
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
            sender: "GAM MED",
            message: smsMessage,
            recipients: [checkerPhone]
          })
        });
        if (smsRes.ok) smsStatus = "DELIVERED";
      } catch (err: any) {
        console.warn("[SMS Gateway Error]:", err.message);
      }
    }

    // 4. Dispatch Email if Resend configured
    let emailStatus = "SIMULATED";
    const resendApiKey = process.env.RESEND_API_KEY;
    if (resendApiKey) {
      try {
        const resendRes = await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: {
            Authorization: `Bearer ${resendApiKey}`,
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
            from: "GAM Med Treasury <alerts@gam-med.com>",
            to: emailPayload.to,
            subject: emailPayload.subject,
            html: emailPayload.html
          })
        });
        if (resendRes.ok) emailStatus = "DELIVERED";
      } catch (err: any) {
        console.warn("[Email Gateway Error]:", err.message);
      }
    }

    return NextResponse.json({
      success: true,
      notificationId: `notif-${Date.now()}`,
      emailStatus,
      smsStatus,
      smsPreview: smsMessage,
      actionUrl: deepLink
    });
  } catch (error: any) {
    return NextResponse.json(
      { success: false, error: error.message || "Failed to trigger notification" },
      { status: 500 }
    );
  }
}
