
'use client';

import { Admission } from '@/lib/types';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { format } from 'date-fns';

interface AdmissionsHistoryTabProps {
  admissions: Admission[];
}

/**
 * == Conceptual UI: Patient's View of Records ==
 *
 * This component acts as part of the "Patient Portal". It displays a history of all past
 * admissions for the patient.
 *
 * Key Features:
 * - **History:** Lists every admission, providing a clear record for the patient.
 * - **Conditional Action:** It includes a "Download Summary" button that is *only* visible
 *   and active for admissions that have been fully discharged and have a `summaryPDF_URL`.
 * - **Secure Link:** Clicking the button would open the `summaryPDF_URL`, which is a secure,
 *   long-lived link to the PDF file stored in Firebase Storage. This is generated by the
 *   `generateDischargeSummaryPDF` Cloud Function.
 */
export function AdmissionsHistoryTab({ admissions }: AdmissionsHistoryTabProps) {
  const isDischarged = (status: Admission['status']) => status === 'Discharged';
  
  return (
    <div className="space-y-4">
       <h3 className="text-xl font-semibold">Admission History</h3>
       <div className="rounded-md border">
        <Table>
            <TableHeader>
                <TableRow>
                    <TableHead>Admission ID</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Admission Date</TableHead>
                    <TableHead>Discharge Date</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Actions</TableHead>
                </TableRow>
            </TableHeader>
            <TableBody>
                {admissions.length > 0 ? (
                    admissions.map((admission) => (
                        <TableRow key={admission.admission_id}>
                            <TableCell className="font-medium">{admission.admission_id}</TableCell>
                            <TableCell>{admission.type}</TableCell>
                            <TableCell>{format(new Date(admission.admission_date), 'PPP')}</TableCell>
                            <TableCell>
                                {admission.discharge_date ? format(new Date(admission.discharge_date), 'PPP') : 'N/A'}
                            </TableCell>
                            <TableCell>
                                <Badge variant={isDischarged(admission.status) ? 'secondary' : 'default'}>
                                    {admission.status}
                                </Badge>
                            </TableCell>
                            <TableCell>
                                {isDischarged(admission.status) && admission.summary_pdf_url ? (
                                    <Button asChild variant="outline" size="sm">
                                        <a href={admission.summary_pdf_url} target="_blank" rel="noopener noreferrer">
                                            <Download className="h-3 w-3 mr-2" />
                                            Summary
                                        </a>
                                    </Button>
                                ) : (
                                   <span className="text-xs text-muted-foreground">N/A</span>
                                )}
                            </TableCell>
                        </TableRow>
                    ))
                ) : (
                    <TableRow>
                        <TableCell colSpan={6} className="h-24 text-center">
                            No admission records found.
                        </TableCell>
                    </TableRow>
                )}
            </TableBody>
        </Table>
       </div>
    </div>
  );
}
